import type { Restaurant } from "./types"

export const restaurants: Restaurant[] = [
  {
    id: "1",
    name: "Pasta Paradise",
    image: "https://images.unsplash.com/photo-1579684947550-22e945225d9a?q=80&w=2574&auto=format&fit=crop",
    description: "Authentic Italian cuisine with homemade pasta and wood-fired pizzas in a cozy atmosphere.",
    rating: 4.7,
    priceLevel: 2,
    distance: 1.2,
    cuisines: ["Italian", "Mediterranean"],
    isOpen: true,
    reactions: {
      love: 124,
      yummy: 89,
      meh: 12,
      nope: 3,
    },
  },
  {
    id: "2",
    name: "Spice Garden",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=2574&auto=format&fit=crop",
    description: "Bold and flavorful Indian dishes with a modern twist, featuring both traditional and fusion options.",
    rating: 4.5,
    priceLevel: 2,
    distance: 0.8,
    cuisines: ["Indian", "Vegetarian"],
    isOpen: true,
    reactions: {
      love: 98,
      yummy: 112,
      meh: 15,
      nope: 5,
    },
  },
  {
    id: "3",
    name: "Sushi Sensation",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=2670&auto=format&fit=crop",
    description: "Premium sushi and Japanese specialties made with fresh, high-quality ingredients by skilled chefs.",
    rating: 4.8,
    priceLevel: 3,
    distance: 2.1,
    cuisines: ["Japanese", "Sushi"],
    isOpen: false,
    reactions: {
      love: 156,
      yummy: 103,
      meh: 8,
      nope: 2,
    },
  },
  {
    id: "4",
    name: "Burger Bistro",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=2598&auto=format&fit=crop",
    description: "Gourmet burgers made with locally-sourced ingredients and unique toppings, plus craft beers.",
    rating: 4.3,
    priceLevel: 2,
    distance: 1.5,
    cuisines: ["American", "Burgers"],
    isOpen: true,
    reactions: {
      love: 87,
      yummy: 95,
      meh: 23,
      nope: 8,
    },
  },
  {
    id: "5",
    name: "Green Plate",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?q=80&w=2574&auto=format&fit=crop",
    description: "Plant-based restaurant offering creative vegan and vegetarian dishes that satisfy even meat-lovers.",
    rating: 4.6,
    priceLevel: 2,
    distance: 1.9,
    cuisines: ["Vegan", "Vegetarian"],
    isOpen: true,
    reactions: {
      love: 76,
      yummy: 82,
      meh: 14,
      nope: 6,
    },
  },
  {
    id: "6",
    name: "Taco Fiesta",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=2680&auto=format&fit=crop",
    description: "Authentic Mexican street food with handmade tortillas, fresh salsas, and margaritas.",
    rating: 4.4,
    priceLevel: 1,
    distance: 0.7,
    cuisines: ["Mexican", "Latin American"],
    isOpen: true,
    reactions: {
      love: 92,
      yummy: 108,
      meh: 18,
      nope: 7,
    },
  },
]

export const trendingRestaurants: Restaurant[] = [
  {
    id: "7",
    name: "Fusion Kitchen",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=2574&auto=format&fit=crop",
    description: "Innovative dishes blending Asian and European techniques with locally-sourced ingredients.",
    rating: 4.9,
    priceLevel: 3,
    distance: 2.3,
    cuisines: ["Asian Fusion", "Contemporary"],
    isOpen: true,
    reactions: {
      love: 187,
      yummy: 142,
      meh: 5,
      nope: 1,
    },
  },
  {
    id: "8",
    name: "Mediterranean Oasis",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=2669&auto=format&fit=crop",
    description: "Authentic Mediterranean cuisine featuring fresh seafood, mezze platters, and wood-fired specialties.",
    rating: 4.7,
    priceLevel: 2,
    distance: 1.6,
    cuisines: ["Mediterranean", "Greek"],
    isOpen: true,
    reactions: {
      love: 134,
      yummy: 98,
      meh: 9,
      nope: 3,
    },
  },
  {
    id: "9",
    name: "Dim Sum Delight",
    image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?q=80&w=2574&auto=format&fit=crop",
    description: "Traditional Chinese dim sum with a contemporary twist, served in an elegant setting.",
    rating: 4.8,
    priceLevel: 3,
    distance: 3.1,
    cuisines: ["Chinese", "Dim Sum"],
    isOpen: false,
    reactions: {
      love: 156,
      yummy: 112,
      meh: 7,
      nope: 2,
    },
  },
]
